name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Run tests
      run: go test ./...
        
    - name: Build for multiple platforms
      run: |
        # Create builds directory
        mkdir -p builds
        
        # Build for multiple platforms
        platforms=(
          "windows/amd64"
          "windows/arm64"
          "linux/amd64"
          "linux/arm64"
          "darwin/amd64"
          "darwin/arm64"
          "freebsd/amd64"
        )
        
        for platform in "${platforms[@]}"; do
          platform_split=(${platform//\// })
          GOOS=${platform_split[0]}
          GOARCH=${platform_split[1]}
          
          output_name="tuneminal-${GOOS}-${GOARCH}"
          if [ $GOOS = "windows" ]; then
            output_name+='.exe'
          fi
          
          echo "Building $output_name"
          GOOS=$GOOS GOARCH=$GOARCH go build -ldflags="-s -w" -o builds/$output_name cmd/tuneminal/main.go
        done
        
        # Create checksums
        cd builds
        sha256sum * > checksums.txt
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: builds/*
        generate_release_notes: true
        draft: false
        prerelease: false

